<?php get_header(); ?>
<?php get_template_part('elements/site-banner'); ?>
<?php get_template_part('elements/site-header'); ?>
<?php get_template_part('elements/section-1'); ?>
<?php get_template_part('elements/section-2'); ?>
<?php get_template_part('elements/section-3'); ?>
<?php get_template_part('elements/section-4'); ?>
<?php get_template_part('elements/portfolio'); ?>
<?php get_template_part('elements/facts'); ?>
<?php get_template_part('elements/contact'); ?>
<?php get_footer(); ?>